#!/bin/sh
feh --bg-fill --random ~/.config/bspwm/rices/emilia/* &

export RICETHEME=$(<"$HOME"/.config/bspwm/rice.cfg)
PATH="$HOME/.config/bspwm/scripts:$PATH"

########### Workspaces

workspaces() {
	name=1
	for monitor in $(bspc query -M); do
		bspc monitor "${monitor}" -n "$name" -d '1' '2' '3' '4' '5' '6' '7'
		let name++
	done
}

workspaces

########### Launch The Rice!!

source LaunchWorld
SetGirlFriendRice
AutoStartApps 

## border ####
bspc config border_width 3
########### bspwm conf

bspc config external_rules_command ~/.config/bspwm/scripts/external_rules
bspc config window_gap 15

bspc config single_monocle true
bspc config split_ratio 0.5
bspc config borderless_monocle true
bspc config gapless_monocle false
bspc config focus_follows_pointer false
bspc config center_pseudo_tiled true

bspc config pointer_modifier mod4
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner
bspc config automatic_scheme longest_side
bspc config initial_polarity second_child
rspc config pointer_motion_interval 16
xset r rate 300 45
# Border colors
bspc config focused_border_color "#076617"
xset b off
xset b 0 0 0

bspc rule -a spotify sticky=on state=floating

#autostart
# emacs -daemon &

bspc rule -a Emacs state=tiled


#rule
bspc rule -a scpad sticky=on state=floating rectangle=1200x800 center=on
dunst &
