#! /bin/sh

wid=$1
class=$2
instance=$3
consequences=$4
title=$(xtitle "$wid")

if [ "$instance" = termite ]; then
	case "$title" in
	ranger)
		echo "state=floating rectangle=811x428+0+0 center=on"
		;;
	zfetch)
		echo "border=off state=floating rectangle=616x354+36+115"
		;;
	sysfetch)
		echo "border=off state=floating rectangle=352x500+36+115"
		;;
	updating)
		echo "state=floating rectangle=510x290+1090+72"
		;;
	musicplayer)
		echo "state=floating rectangle=630x215+0+0 center=on"
		;;
	esac
fi

main() {
	case "$class" in
    Ulauncher)
		eval "$consequences"
		[ "$state" ] || echo "state=floating focus=on center=on border=off" 
		;;
	mpv)
		eval "$consequences"
		[ "$state" ] || echo "state=floating focus=on center=on rectangle=925x519+0+0 border=off"
		;;
	Viewnior)
		eval "$consequences"
		[ "$state" ] || echo "state=floating focus=on center=on border=off"
		;;
	whatsapp-nativefier-d40211)
		eval "$consequences"
		[ "$state" ] || echo "state=pseudo_tiled center=on follow=on rectangle=930x617+0+0"
		;;
	retroarch)
		eval "$consequences"
		[ "$state" ] || echo "state=pseudo_tiled desktop=^6 center=on follow=on border=off"
		;;
	ranger)
		eval "$consequences"
		[ "$state" ] || echo "state=floating rectangle=811x316+0+0 center=on"
		;;
	Pavucontrol)
		eval "$consequences"
		[ "$state" ] || echo "state=floating follow=on center=on"
		;;
	Virt-manager)
		eval "$consequences"
		[ "$state" ] || echo "state=floating desktop=^5 follow=on center=on"
		;;
	Transmission-gtk)
		eval "$consequences"
		[ "$state" ] || echo " follow=on"
		;;
	esac
}

main
case "$instance" in
Toolkit)
	eval "$consequences"
	[ "$state" ] || echo "state=floating sticky=on rectangle=500x290+1054+593"
	;;
esac
